### ISSUE TITLE
name => namespace

### ISSUE THREAD

**Issue by inutano** [dbcls/togoid-config#10]
`target` 要素に `name` が残っていますがこれは `namespace` に修正する必要があります、他のファイルも確認おねがいします
https://github.com/dbcls/togoid-config/blob/main/link/chembl.target-pdb/config.yaml

**Comment by yatsuzuka-nbdc** [comment]
`name` -> `namespace` に修正しました。

**Comment by inutano** [comment]
@yatsuzuka-nbdc ありがとうございます！こちらがまだ `name:` のままなのですが、コミットは八塚さん、コメントには信定さんとあります。ご確認ください〜
https://github.com/dbcls/togoid-config/blob/main/link/hint-uniprot/config.yaml

**Comment by yatsuzuka-nbdc** [comment]
すみません。hint-uniprot 修正しました。

**Comment by inutano** [comment]
現時点で `namespace:` が残ってるやつ:

```
link/ensembl-ensembl.protein/config.yaml
link/interpro-go/config.yaml
link/interpro-pdb/config.yaml
link/interpro-pfam/config.yaml
link/interpro-pubmed/config.yaml
link/interpro-reactome/config.yaml
link/kegg.compound-kegg.reaction/config.yaml
```

コミットログから担当は @skwsm @sh-ikeda @yucca-t-k だそうです、ご確認ください〜

**Comment by sh-ikeda** [comment]
interpro修正いたしました。
