### ISSUE TITLE
IDのペア作成で議論したいこと

### ISSUE THREAD

**Issue by hiromasaono** [dbcls/togoid-config#13]
どのIDペアで、どういう問題･課題が発生しているかのメモを書いて、後日対応を協議します。

**Comment by yayamamo** [comment]
- ChEMBL内で参照されているMeSHのURIはidentifiers.orgなのに対し、MeSH RDFのSPARQLエンドポイントでは、NIHのURIが利用されているので、ChEMBLとMeSHのRDFデータを相互に利用したい場合は変換が必要になる。
SPARQLクエリ内で行う場合は、SUBSTR、STR、URIなどの関数を用いてBINDするか、TogoIDが変換用のSPARQLエンドポイントを立てて、そこに連合検索をかけるか。
- faldoやdoiの参照URIがhttpもしくはhttpsであったり、wwwがあったりなかったりする例がある。これは気がつきにくいので、一通り全てのRDFデータでこれらの相違を一度確認しておいた方が良いかもしれない。

**Comment by yucca-t-k** [comment]
*  id-configの中で、namespaceとして複数の可能性が考えられるとき、どれを採用するか。全体で統一するのか、DBペア同士で決めていいのか 
      * Background: PubChem の IDについて、identifiers.org では 数字列 （^\d+$）だが、PubChemのRDFではSubstanceならSID, CompoundならCIDが数字の前につく。（たとえば http://identifiers.org/pubchem.substance/3303 は PubChem RDFでは http://rdf.ncbi.nlm.nih.gov/pubchem/substance/SID3303 ）。どちらのnamespaceを使うかで出力されるIDの形が変わる

**Comment by yucca-t-k** [comment]
* KEGG Drug -> KEGG Disease： Drug（A）からDisease（B）へ直接つながる関係  （AはBの治療薬）にどれを使ったらいいかわからない

**Comment by yayamamo** [comment]
> id-configの中で、namespaceとして複数の可能性が考えられるとき、どれを採用するか。全体で統一するのか、DBペア同士で決めていいのか
> * Background: PubChem の IDについて、identifiers.org では 数字列 （^\d+$）だが、PubChemのRDFではSubstanceならSID, CompoundならCIDが数字の前につく。（たとえば http://identifiers.org/pubchem.substance/3303 は PubChem RDFでは http://rdf.ncbi.nlm.nih.gov/pubchem/substance/SID3303 ）。どちらのnamespaceを使うかで出力されるIDの形が変わる

PubChemについては、Tokyo Manifestoに従って、PubChem RDFを採用するのが良いのではないでしょうか。
http://hackathon3.dbcls.jp/wiki/URI
