### ISSUE TITLE
修正：TogoVar

### ISSUE THREAD

**Issue by yatsuzuka-nbdc** [dbcls/togoid-config#40]

**Comment by mitsuhashi** [comment]
### 2021/3/12現在の進捗

件数が多いため、togovar-clinvarとtogovar-medgen以外のデータは、オリジナルデータからタブ区切りファイルを作成（豊岡さん）し、https://togovar.biosciencedbc.jp/public/togoid/ に置いている。updateはここからcurlコマンドでダウンロードするように記載している。

#### 完了

- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-clinvar
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-medgen

#### チェック可能。データを差し替える予定あり

- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_gene
  - TODO: togovar : ENSG = 1 : Nの場合にENSGのIDを取り逃がしているのを修正
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_transcript
  - TODO: togovar : ENST = 1 : Nの場合にENSTのIDを取り逃がしているのを修正
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-refseq_rna
  -  TODO: NM_ 以外からはじまるものも混在している。TogoIDで扱うPREFIXとの対応を要確認
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-hgnc
  - TODO: Gene symbolではなくhgncidを出力するように修正
- https://github.com/dbcls/togoid-config/tree/main/link/togovar-dbsnp
  - TODO: dbSNP rs番号にCOSMICのIDが結合して出力されている行があるので除去する

#### 作業中
- https://github.com/dbcls/togoid-config/tree/main/link/togovar-ncbigene
  -  TODO: NCBIGene IDの列が一切出力されていないので修正
- https://github.com/dbcls/togoid-config/tree/main/link/togovar-pubmed
  -  TODO:  PubTatorCentral(dbSNPとPMIDのペア）とtogovar-dbsnpのデータをjoinコマンドでJoinして作成予定（作業者：三橋）

**Comment by mitsuhashi** [comment]
### 2021/3/16現在の進捗

#### 完了

- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-clinvar
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-medgen

#### 3/16中には完成予定

- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_gene
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_transcript
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-refseq_rna
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-hgnc
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-dbsnp
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-pubmed
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ncbigene

#### 作成スクリプト
- https://togovar.biosciencedbc.jp/public/togoid/scripts/

**Comment by mitsuhashi** [comment]
### 2021/3/17現在の進捗

#### 完了

- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-clinvar
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-medgen
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_gene
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ensembl_transcript
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-refseq_rna
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-hgnc
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-dbsnp
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-pubmed
- https://github.com/dbcls/togoid-config/tree/refactoring/config-todo/togovar-ncbigene

#### 備忘
- 上記のtogoid-config(togovar-clinvarとtogovar-medgenを除く)は以下のURLのtsvファイル群をダウンロードしているだけである。
  - https://togovar.biosciencedbc.jp/public/togoid/
- tsvファイルを作成するためのスクリプトは以下の場所にある。ただしそのままでは動かない。
  - https://togovar.biosciencedbc.jp/public/togoid/scripts/
