### ISSUE TITLE
修正：uniprot-reactome_reaction, uniprot-reactome_pathway

### ISSUE THREAD

**Issue by yatsuzuka-nbdc** [dbcls/togoid-config#41]

**Comment by hiromasaono** [comment]
https://github.com/dbcls/togoid-config/blob/refactoring/config/reactome_pathway-reactome_reaction/query.rq を参考にしてみてたのですが、このクエリで取れるIDのペアについて調べてみると、
<img width="866" alt="スクリーンショット 2021-03-16 11 17 27" src="https://user-images.githubusercontent.com/2275313/111246225-3a132580-8649-11eb-97fc-f439f38264a0.png">

R-CEL-3238698
https://reactome.org/content/detail/R-HSA-3238698

R-CEL-3247837
https://reactome.org/content/detail/R-CEL-3247837

**Comment by hiromasaono** [comment]
もともとのUniprot-reactomeにはなぜか、PDB-Uniprotのデータが入っていました。

**Comment by hiromasaono** [comment]
uniprot-reactome_pathway は守屋さんスクリプト(sparql_thread.pl)で更新するように変更しました。
