### ISSUE TITLE
chembl_target-intact

### ISSUE THREAD

**Issue by yatsuzuka-nbdc** [dbcls/togoid-config#53]
【問題】
ペアデータで、IntactのIDがおかしい。
正しいID：（例）EBI-2307691
ペアデータに含まれているIntactのID：（例）Q9UN88　←Uniprot ID

【原因】
ペアデータはChembl RDFから取得しているが、
Chembl RDFが保有するIntactの参照情報(IntactCrossReference)のURLが、
http://identifiers.org/intact/Q9UN88　のようになっており、
（このURLはidentifiers.orgではサポートされていない）
EBI-xxxxxx というIDは存在しない。
相互作用に関わるタンパク質のIDをそのまま使っている？

【対応】
configから除外する？

**Comment by hiromasaono** [comment]
- chembl_targetIDにはヒットせず、chembl_compoundIDが取得されている。
- chembl_compoundにリンクしているchembl_targetID の相手のintact IDが取得されている。
- intactのIDは、Interaction ACを取らないといけない? 取れる?
