### ISSUE TITLE
wikipathways-uniprot

### ISSUE THREAD

**Issue by yatsuzuka-nbdc** [dbcls/togoid-config#54]
【問題】
ペアデータで、Uniprot IDにおかしなものが含まれている。
１．IDが数字だけのもの
例１：694009

２．PDB IDらしきもの
例２：6ZSL

【原因】
wikipathwaysの中で、これらは"Uniprot ID"として扱われているため。
(dc:source 'Uniprot-TrEMBL')
例１：694009
https://www.wikipathways.org/index.php/Pathway:WP4880
参照

例２：6ZSL
https://www.wikipathways.org/index.php/Pathway:WP5039
参照

【対応】
そのままにする？

**Comment by hiromasaono** [comment]
守屋さんがconfig.yamlのmethodにUniprotIDの正規表現で取るように修正済み。
Wikipathways自体のミスアノテーションが時々あることを確認。
