### ISSUE TITLE
pubchem_compound-drugbank, ensg, uniprot

### ISSUE THREAD

**Issue by nobusada-nbdc** [dbcls/togoid-config#56]
月曜のミーティングを受けて以下３つのconfigを作成しました。developに入れましたのでご確認お願いします。
pubchem_compound-drugbank
pubchem_compound-ensembl_gene
pubchem_compound-uniprot

**Comment by hiromasaono** [comment]
https://github.com/dbcls/togoid-config/commit/6f2dce0dd75c86fb3085e02d5da356c20547bd18
config に移動しました。
@nobusada-nbdc さん、ありがとうございました。
