### ISSUE TITLE
IDペアに重複行がある

### ISSUE THREAD

**Issue by hiromasaono** [dbcls/togoid-config#64]
- refseq_rna-pubmed　@meso-cacase 
- sra_accession-bioproject @inutano 
- sra_accession-biosample @inutano  
- sra_accession-sra_experiment @inutano 
- sra_accession-sra_run @inutano 

- refseq_rna-ncbigene @meso-cacase 
- 行数164,535に対して、ncbigene-refseq_rnaは行数 37,549,289。差が大きいが原因は？古い ID を対象外にしているとか？(池田)

**Comment by inutano** [comment]
SRA accession のやつは #65 で修正しましたんで確認&マージおねがいします〜

**Comment by meso-cacase** [comment]
- refseq_rna-ncbigene には重複行はありません。
  - ただし他の refseq_* とともに重複行を除く処理を入れておこうと思います。
- refseq_rna-ncbigene はヒトのみ、ncbigene-refseq_rna は他の生物種も含まれていることが、行数の差が大きい理由です。

**Comment by hiromasaono** [comment]
@meso-cacase  すみません、ペアの記載を間違えてました。　
refseq_rna-pubmed　ですね。
NM_001615        2377475
NM_001615        2377475
NM_001648        2436946
NM_001648        2436946
NM_004350        8437866
NM_004350        8437866

**Comment by meso-cacase** [comment]
refseq_*-* に重複行を除く処理を加えました
https://github.com/dbcls/togoid-config/commit/2a7fd9b062622fd18d30f014881da20e54beb6e2

**Comment by hiromasaono** [comment]
@inutano @meso-cacase ご対応ありがとうございました!
