### ISSUE TITLE
chembl 系の reverse

### ISSUE THREAD

**Issue by moriya-dbcls** [dbcls/togoid-config#68]
chembl_compound-*, chembl_target-* には reverse を指定していないみたいですが、方針なのでしょうか？
TogoID API では reverse がないと逆引きは行わないので、少なくともTogoSite で使う
* chembl_compound-chebi
* chembl_compound-chembl_target 
は reverse を入れてほしいです

**Comment by hiromasaono** [comment]
@moriya-dbcls 当初、chembl_compound-, chembl_target- は reverse 指定してなかったのですが、その後入れるようにして準備はしていました。これから @nobusada-nbdc さんがconfig を書き換えてくれますので、しばしお待ち下さい。

**Comment by nobusada-nbdc** [comment]
@moriya-dbcls chembl_compound-, chembl_target- の reverseをconfigに追記しました。
