### ISSUE TITLE
markdown 記法がおかしい

### ISSUE THREAD

**Issue by inutano** [dbcls/togoid-config#7]
たとえばこれ。拡張子は .md ですが markdown 記法ではない模様です。markdown でレンダリングされるように書いたほうがよいかとおもいます。 https://github.github.com/gfm/
https://github.com/dbcls/togoid-config/blob/main/link/drugbank-pubchem/README.md

それから今確認したところでは drugbank-pubchem, drugbank-uniprot の説明がおかしい（入れ替わっている？）みたいです。

@yatsuzuka-nbdc

**Comment by yatsuzuka-nbdc** [comment]
drugbank-* のREADMEは全て修正しました。

**Comment by inutano** [comment]
@yatsuzuka-nbdc ありがとうございます！他のlinkのｍarkdownは問題ないでしょうか？

**Comment by yatsuzuka-nbdc** [comment]
私がコミットして、かつREADME.mdがあるのはdrugbank-*だけです。

**Comment by inutano** [comment]
ありがとうございます！
