### ISSUE TITLE
名前空間の統一

### ISSUE THREAD

**Issue by inutano** [dbcls/togoid-config#8]
たとえば ensembl 
https://registry.identifiers.org/registry/ensembl

prefix は ensembl だが複数のデータタイプのIDがある (gene, transcript, protein etc.) ので、リンクペアの名前付けのときにどのように書くか決める必要があります。

`ensembl.gene` のようにするのがよさそうですがどうでしょうか。

**Comment by skwsm** [comment]
僕は、gene は ensembl、transcript は ensembl.transcript、protein は ensembl.protein にしていますが、これに揃えて、というのがあれば揃えます。ensembl.ensg は賛成しませんが。
